In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("../data/StudentsPerformance.csv")
df.head()

In [ ]:
df.shape

In [ ]:
df.info()

In [ ]:
df.describe()

# Task 2: Descriptive Statistics

In this task, descriptive statistics are calculated for math score, reading score, and writing score. The analysis includes mean, median, mode, standard deviation, minimum, maximum, mean vs median comparison, groupby analysis, and observations.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("../data/StudentsPerformance.csv")
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [2]:
score_columns = ['math score', 'reading score', 'writing score']

df[score_columns].head()

   math score  reading score  writing score
0          72             72             74
1          69             90             88
2          90             95             93
3          47             57             44
4          76             78             75

In [3]:
mean_values = df[score_columns].mean()
mean_values

math score       66.089
reading score    69.169
writing score    68.054
dtype: float64

In [4]:
median_values = df[score_columns].median()
median_values

math score       66.0
reading score    70.0
writing score    69.0
dtype: float64

In [5]:
mode_values = df[score_columns].mode().iloc[0]
mode_values

math score       65
reading score    72
writing score    74
Name: 0, dtype: int64

In [6]:
std_values = df[score_columns].std()
std_values

math score       15.163080
reading score    14.600192
writing score    15.195657
dtype: float64

In [7]:
min_values = df[score_columns].min()
min_values

math score        0
reading score    17
writing score    10
dtype: int64

In [8]:
max_values = df[score_columns].max()
max_values

math score       100
reading score    100
writing score    100
dtype: int64

In [9]:
statistics_table = pd.DataFrame({
    'Mean': mean_values,
    'Median': median_values,
    'Mode': mode_values,
    'Standard Deviation': std_values,
    'Minimum': min_values,
    'Maximum': max_values
})

statistics_table

                 Mean  Median  Mode  Standard Deviation  Minimum  Maximum
math score     66.089    66.0    65           15.163080        0      100
reading score  69.169    70.0    72           14.600192       17      100
writing score  68.054    69.0    74           15.195657       10      100

In [11]:
gender_group = df.groupby('gender')[score_columns].mean()
gender_group

        math score  reading score  writing score
gender
female   63.633205      72.608108      72.467181
male     68.728216      65.473029      63.311203

In [10]:
test_prep_group = df.groupby('test preparation course')[score_columns].mean()
test_prep_group

                         math score  reading score  writing score
test preparation course
completed                 69.695531      73.893855      74.418994
none                      64.077882      66.534268      64.504673

In [12]:
lunch_group = df.groupby('lunch')[score_columns].mean()
lunch_group

              math score  reading score  writing score
lunch
free/reduced   58.921127      64.653521      63.022535
standard       70.034109      71.654264      70.823256

# Task 3: Data Cleaning

In this task, a messy version of the dataset is created to demonstrate data cleaning. The cleaning process includes identifying missing values, duplicate rows, and outliers. Missing values are handled, duplicates are removed, invalid score values are cleaned, and the final cleaned dataset is saved.

In [13]:
df = pd.read_csv("../data/StudentsPerformance.csv")
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [14]:
messy_df = df.copy()

# Adding missing values
messy_df.loc[0, 'math score'] = np.nan
messy_df.loc[1, 'reading score'] = np.nan
messy_df.loc[2, 'writing score'] = np.nan

# Adding duplicate rows
messy_df = pd.concat([messy_df, messy_df.iloc[0:5]], ignore_index=True)

# Adding outliers / invalid values
messy_df.loc[10, 'math score'] = 150
messy_df.loc[11, 'reading score'] = -20
messy_df.loc[12, 'writing score'] = 130

messy_df.head(15)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,NaN,72.0,74.0
1,female,group C,some college,standard,completed,69.0,NaN,88.0
2,female,group B,master's degree,standard,none,90.0,95.0,NaN
3,male,group A,associate's degree,free/reduced,none,47.0,57.0,44.0
4,male,group C,some college,standard,none,76.0,78.0,75.0
5,female,group B,associate's degree,standard,none,71.0,83.0,78.0
6,female,group B,some college,standard,completed,88.0,95.0,92.0
7,male,group B,some college,free/reduced,none,40.0,43.0,39.0
8,male,group D,high school,free/reduced,completed,64.0,64.0,67.0
9,female,group B,high school,free/reduced,none,38.0,60.0,50.0
10,male,group C,associate's degree,standard,none,150.0,54.0,52.0
11,male,group D,associate's degree,standard,none,40.0,-20.0,43.0
12,female,group B,high school,standard,none,65.0,81.0,130.0
13,male,group A,some college,standard,completed,78.0,72.0,70.0
14,female,group A,master's degree,standard,none,50.0,53.0,58.0

In [15]:
missing_values_before = messy_df.isnull().sum()
missing_values_before

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     2
reading score                  2
writing score                  2
dtype: int64

In [19]:
duplicates_before = messy_df.duplicated().sum()
duplicates_before

np.int64(5)

In [16]:
messy_df[['math score', 'reading score', 'writing score']].describe()

        math score  reading score  writing score
count  1003.000000    1003.000000    1003.000000
mean     66.192423      69.101695      68.094716
std      15.400892      14.853631      15.311992
min       0.000000     -20.000000      10.000000
25%      57.000000      59.000000      57.500000
50%      66.000000      70.000000      69.000000
75%      77.000000      79.000000      79.000000
max     150.000000     100.000000     130.000000

In [17]:
before_rows = messy_df.shape[0]
before_missing = messy_df.isnull().sum().sum()
before_duplicates = messy_df.duplicated().sum()

print("Rows before cleaning:", before_rows)
print("Missing values before cleaning:", before_missing)
print("Duplicate rows before cleaning:", before_duplicates)

Rows before cleaning: 1005
Missing values before cleaning: 6
Duplicate rows before cleaning: 5

In [18]:
messy_df['math score'] = messy_df['math score'].fillna(messy_df['math score'].median())
messy_df['reading score'] = messy_df['reading score'].fillna(messy_df['reading score'].median())
messy_df['writing score'] = messy_df['writing score'].fillna(messy_df['writing score'].median())

messy_df.isnull().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [20]:
messy_df = messy_df.drop_duplicates()

messy_df.duplicated().sum()

np.int64(0)

In [21]:
cleaned_df = messy_df[
    (messy_df['math score'] >= 0) & (messy_df['math score'] <= 100) &
    (messy_df['reading score'] >= 0) & (messy_df['reading score'] <= 100) &
    (messy_df['writing score'] >= 0) & (messy_df['writing score'] <= 100)
]

cleaned_df[['math score', 'reading score', 'writing score']].describe()

       math score  reading score  writing score
count  997.000000     997.000000     997.000000
mean    66.118355      69.169509      68.066199
std     15.159991      14.584415      15.167923
min      0.000000      17.000000      10.000000
25%     57.000000      59.000000      58.000000
50%     66.000000      70.000000      69.000000
75%     77.000000      79.000000      79.000000
max    100.000000     100.000000     100.000000

In [24]:
after_rows = cleaned_df.shape[0]
after_missing = cleaned_df.isnull().sum().sum()
after_duplicates = cleaned_df.duplicated().sum()

print("Rows after cleaning:", after_rows)
print("Missing values after cleaning:", after_missing)
print("Duplicate rows after cleaning:", after_duplicates)

Rows after cleaning: 997
Missing values after cleaning: 0
Duplicate rows after cleaning: 0

In [25]:
cleaning_comparison = pd.DataFrame({
    'Before Cleaning': [before_rows, before_missing, before_duplicates],
    'After Cleaning': [after_rows, after_missing, after_duplicates]
}, index=['Total Rows', 'Missing Values', 'Duplicate Rows'])

cleaning_comparison

                Before Cleaning  After Cleaning
Total Rows                 1005             997
Missing Values                6               0
Duplicate Rows                5               0

In [26]:
cleaned_df.to_csv("../data/Cleaned_StudentsPerformance.csv", index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.